services:
  linkdownloaderbot:
    build: .
    container_name: linkdownloaderbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./main.py:/app/main.py:ro
      - ./config.py:/app/config.py:ro
      - ./data:/app/data
